# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
class VagrantPlugins::ProviderVirtualBox::Action::Network
  def dhcp_server_matches_config?(dhcp_server, config)
    true
  end
end

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.network "private_network", type: "dhcp", name: "vboxnet1"
  #config.ssh.insert_key = false
  #config.ssh.username = "carmine.fabrizio"
  #config.ssh.password = "Laboratorio1"
  #config.ssh.private_key_path = ["~/.ssh/id_rsa.pub" , "~/.vagrant.d/insecure_private_key"]

  config.vm.define "web01" do |web01|
   web01.vm.hostname = "web01"
   #web01.vm.network "private_network" , type: "dhcp"
   #master.vm.network "forwarded_port", guest: 80, guest_ip: "172.28.128.3", host: 8080, host_ip: "127.0.0.1"
   web01.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "512"
    end
   web01.vm.provision "shell", inline: <<-SHELL
     apt-get update -y
  SHELL
   end

  config.vm.define "web02" do |web02|
   web02.vm.hostname = "web02"
   #web02.vm.network "private_network", type: "dhcp"
   #cluster01.vm.network "forwarded_port", guest: 80, guest_ip: "10.0.2.15", host: 8081, host_ip: "127.0.0.1"
   web02.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "512"
   end
   web02.vm.provision "shell", inline: <<-SHELL
     apt-get update -y
  SHELL
  end

  config.vm.define "db01" do |db01|
   db01.vm.hostname = "db"
   #db01.vm.network "private_network", type: "dhcp"
   #cluster01.vm.network "forwarded_port", guest: 80, guest_ip: "10.0.2.17", host: 8082, host_ip: "127.0.0.1"
   db01.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "512"
   end   
   db01.vm.provision "shell", inline: <<-SHELL
     apt-get update -y
  SHELL
  end
  config.vm.define "db02" do |db02|
   db02.vm.hostname = "db"
   #db01.vm.network "private_network", type: "dhcp"
   #cluster01.vm.network "forwarded_port", guest: 80, guest_ip: "10.0.2.17", host: 8082, host_ip: "127.0.0.1"
   db02.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "512"
   end   
   db02.vm.provision "shell", inline: <<-SHELL
     apt-get update -y
  SHELL
  end
  #config.vm.provision "ansible" do |ansible|
   # ansible.playbook = "user.yml"
  #end
end
